### ISSUE TITLE
有关XLM的训练结果

### ISSUE THREAD

**Issue by HuihuiChyan** [kodenii/CoSDA-ML#1]
作者您好！在FOLLOW您的工作的过程中，我发现XLM的模型很不稳定，经常不收敛，相比较之下BERT就稳定很多。不知道您有没有观察到类似的现象？还是可能我参数设置有问题？

**Comment by kodenii** [comment]
因为Code-switch会增加训练难度，因此有些基础模型在训练超参数设置（学习率这种）不好的情况下容易无法收敛。我们建议更细致的检查/搜索一下学习率这种超参数。
我们在实验过程中也发现XLM不如BERT稳定，这可能与预训练模型本身的一些训练方法有关。
