### ISSUE TITLE
How to customize?

### ISSUE THREAD

**Issue by BarahFazili** [kodenii/CoSDA-ML#3]
1. How to customize the execution for a subset of data restricted to fewer languages?
2. How to access the trained model directly without performing an evaluation task?

**Comment by kodenii** [comment]
1. You can specify a new dataset loader script in configuration file (dataset.tool) to customize the execution.
2. You can use some PyTorch built-in tools, such as '''load_state_dict(strict=False)''', to load the BERT or XLM part of the checkpoint in other model.
